name: Staging Deployment

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
    
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: 📦 Install Dependencies
      run: npm ci
    
    - name: 🧪 Run Tests
      run: npm test
    
    - name: 📊 Generate Coverage Report
      run: npm run test:coverage
    
    - name: 💬 Comment PR with Test Results
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const coverage = JSON.parse(fs.readFileSync('./coverage/coverage-summary.json', 'utf8'));
          
          const comment = `## 🧪 Staging Test Results
          
          ✅ All tests passed!
          
          ### Coverage Summary:
          - **Statements**: ${coverage.total.statements.pct}%
          - **Branches**: ${coverage.total.branches.pct}%
          - **Functions**: ${coverage.total.functions.pct}%
          - **Lines**: ${coverage.total.lines.pct}%
          
          📊 [Full Coverage Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
    
    - name: ✅ Staging Validation Complete
      run: echo "✅ Staging tests passed - ready for production!"
